name: Dev-Container

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - .devcontainer/**/*
  push:
    branches:
      - master
    paths:
      - .devcontainer/**/*

jobs:
  docker:
    name: Docker ${{ github.event_name == 'push' && 'Push' || 'Build' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: docker build --tag ghcr.io/${{ github.repository }}:devcontainer .devcontainer

      - name: Push
        if: ${{ github.event_name == 'push' }}
        run: docker push ghcr.io/${{ github.repository }}:devcontainer
