name: Dev Container

on:
  push:
  workflow_dispatch:
    inputs:
        push:
          description: 'Realizar el push de la imagen'
          type: boolean
          default: false

  workflow_call:
    inputs:
      push:
        description: 'Realizar el push de la imagen'
        type: boolean
        default: false

jobs:
  docker:
    name: Docker ${{ inputs.push && 'Push' || 'Build' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: docker build --tag ghcr.io/${{ github.repository }}:devcontainer .devcontainer

      - name: Push
        if: ${{ inputs.push }}
        run: docker push ghcr.io/${{ github.repository }}:devcontainer
