name: Release
on:
  workflow_dispatch:

jobs:
  semantic-release:
    name: Semantic-Release
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: ghcr.io/${{ github.repository }}:devcontainer
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git config --global --add safe.directory $(pwd)
      - uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
            conventional-changelog-conventionalcommits
            semantic-release-github-actions-tags
