name: Test
on:
  workflow_call:
    inputs:
      devcontainer:
        description: 'Devcontainer'
        type: string
      command:
        description: 'Command to Test'
        type: string
        default: 'pre-commit run --show-diff-on-failure --color=always --all-files'
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths-ignore:
      - '.github/**/*'
      - '.pre-commit-config.yaml'
      - '.releaserc.yaml'
      - '.gitignore'

jobs:
  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: ${{ inputs.devcontainer && inputs.devcontainer || 'ghcr.io/vmvarela/workflows:devcontainer' }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
        TEST_COMMAND: ${{ inputs.command && inputs.command || 'pre-commit run --show-diff-on-failure --color=always --all-files' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git config --global --add safe.directory $(pwd)
      - run: ${{ env.TEST_COMMAND }}
